import {
  MessageSquare, Send, Users, Filter, ArrowUpDown, Reply, Search, UserPlus,
  GitFork, Sparkles, Zap, Clock, MessageCircle, CheckCircle2, Settings, Play,
  Bot, Globe, Brain, TestTube, Database, BookOpen,
  Briefcase, Building, Layers, FileText, Rocket,
  LayoutTemplate, Palette, Monitor, Smartphone, Eye, Save, GripVertical, Plus,
  Megaphone, Target, DollarSign, Image, BarChart, TrendingUp,
  Phone, Mic, Shield, Headphones, PhoneCall, Hash,
  Star, Link, Copy, ThumbsUp,
  Satellite, AlertTriangle, MapPin, Radio, Bell,
  Home, Banknote, ScanSearch, ShoppingCart, Lock,
  Code, Columns, FormInput, List, Type,
  Command, PieChart,
  Camera, History, Upload, Download,
  ShoppingBag, Tag,
  Share2, Percent,
  Bolt, Wand2,
  HelpCircle, CircleDot,
  Mail, Plug
} from "lucide-react";
import type { TutorialStep } from "./tutorial-overlay";

export const SITE_BUILDER_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to Site Architect", description: "This tutorial will walk you through building your first website in under 2 minutes. You'll learn how to generate, customize, and publish a professional site using AI.", icon: Sparkles, position: "center" },
  { id: "prompt", title: "Step 1: Describe Your Site", description: "Type a description of the website you want to build. Be specific — mention your business type, style preferences, and key sections you need. For example: \"A modern dental clinic website with booking, services, and team sections.\"", icon: Send, targetSelector: "[data-testid='input-prompt']", position: "bottom-left", tip: "The more detail you give, the better the AI generates your site." },
  { id: "generate", title: "Step 2: Generate", description: "Click the send button (or press Enter) to generate your website. The AI will create a complete multi-section site with your theme, content, and layout in seconds.", icon: Rocket, targetSelector: "[data-testid='button-generate']", position: "bottom-left", action: "Click Generate after typing your prompt" },
  { id: "templates", title: "Or Start from a Template", description: "Don't want to start from scratch? Browse the Template Gallery for pre-built designs across industries like fitness, law, restaurants, and more. Pick one and customize it.", icon: Palette, targetSelector: "[data-testid='button-open-templates']", position: "bottom-left", tip: "Templates are fully editable — use them as starting points." },
  { id: "preview", title: "Step 3: Preview Your Site", description: "Once generated, your full website appears in the preview panel on the right. Scroll through to see every section the AI built for you.", fallbackDescription: "After you generate a site, it will appear in the preview panel on the right. You'll be able to scroll through every section the AI built.", icon: Monitor, targetSelector: "[data-testid='preview-canvas']", position: "top-center" },
  { id: "responsive", title: "Check Mobile View", description: "Switch between desktop and mobile previews to see how your site looks on different devices. Every generated site is automatically responsive.", icon: Smartphone, targetSelector: "[data-testid='button-view-mobile']", position: "top-center", tip: "Always check mobile view — most visitors browse on phones." },
  { id: "edit-mode", title: "Step 4: Edit Mode", description: "Click 'Edit Mode' to unlock section-level editing. You can drag sections to reorder them, edit content inline, delete sections you don't need, or add new ones.", fallbackDescription: "After generating a site, an 'Edit Mode' button appears in the toolbar. It unlocks section-level editing — drag to reorder, edit inline, delete, or add new sections.", icon: Eye, targetSelector: "[data-testid='button-toggle-edit-mode']", position: "top-center", action: "Turn on Edit Mode to customize sections" },
  { id: "drag-sections", title: "Drag to Reorder", description: "In Edit Mode, grab any section by its handle and drag it to a new position. Build the exact page flow you want — hero first, then features, testimonials, pricing, and contact.", icon: GripVertical, position: "center", tip: "Common order: Hero → Features → Testimonials → Pricing → Contact" },
  { id: "add-sections", title: "Add New Sections", description: "Click the '+' button at the bottom of your site in Edit Mode to add new sections: Hero, Features, Testimonials, Pricing, Stats, FAQ, Gallery, Contact, and more.", icon: Plus, position: "center" },
  { id: "save", title: "Step 5: Save Your Work", description: "Click 'Save' to store your design. You can name it, create multiple versions, and come back to edit anytime from 'My Designs'.", icon: Save, targetSelector: "[data-testid='button-save-design']", position: "top-right", tip: "Every save creates a version — you can rollback to any previous version." },
  { id: "publish", title: "Step 6: Publish", description: "When you're happy with your site, click 'Publish' to make it live. You can connect a custom domain from the Domains page for a professional URL.", icon: Globe, targetSelector: "[data-testid='button-publish']", position: "top-right" },
  { id: "done", title: "You're Ready!", description: "That's everything you need to build professional websites with AI. Start by describing your business in the prompt box — your first site is just one sentence away.", icon: CheckCircle2, position: "center" },
];

export const INBOX_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to Unified Inbox", description: "Your central hub for all customer conversations. Manage SMS, Instagram, email, and WhatsApp messages in one place — across all your sub-accounts.", icon: MessageSquare, position: "center" },
  { id: "account-select", title: "Select Your Account", description: "Use the account dropdown to switch between sub-accounts. Each account has its own conversation threads, contacts, and messaging history.", icon: Users, targetSelector: "[data-testid='select-account']", position: "bottom-left", tip: "You can manage multiple businesses from one dashboard." },
  { id: "conversations", title: "Conversation List", description: "The left panel shows all your active conversations. Each thread displays the contact name, last message preview, timestamp, and channel badge (SMS, Instagram, etc.).", icon: MessageCircle, position: "center", fallbackDescription: "When messages come in, they appear as conversation threads on the left. Click any conversation to view the full message history." },
  { id: "compose", title: "Send a Message", description: "Type your message in the compose box and hit Send. Messages go out via the channel the conversation was started on — SMS, WhatsApp, or Instagram.", icon: Send, targetSelector: "[data-testid='button-send']", position: "top-center", action: "Type a message and click Send" },
  { id: "channels", title: "Multi-Channel Support", description: "Nexus automatically detects the channel for each conversation. SMS messages route through Twilio, Instagram through Meta, and WhatsApp through the Business API.", icon: ArrowUpDown, position: "center", tip: "Replies go out on the same channel the customer used to reach you." },
  { id: "ai-auto-reply", title: "AI Auto-Reply", description: "When a customer texts your Twilio number, the AI auto-reply kicks in using the bot persona you trained. It handles common questions, books appointments, and follows up — even when you're offline.", icon: Bot, position: "center", tip: "Train your bot persona in Neural Trainer for smarter auto-replies." },
  { id: "contacts", title: "Contact Management", description: "Every conversation automatically creates a contact record. You can see phone numbers, email addresses, and the full history of every interaction with each customer.", icon: UserPlus, position: "center" },
  { id: "done", title: "You're Connected!", description: "You now know how to manage all your customer conversations from one place. New messages will appear in real-time. Head to Neural Trainer to set up AI auto-replies.", icon: CheckCircle2, position: "center" },
];

export const WORKFLOW_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to Workflows", description: "Build powerful automations that run on autopilot. Create sequences of actions triggered by events like new messages, form submissions, or time-based schedules.", icon: GitFork, position: "center" },
  { id: "ai-generate", title: "AI Workflow Generator", description: "Click 'Generate with AI' to describe what you want in plain English. The AI will create a complete workflow with triggers, delays, conditions, and actions — instantly.", icon: Sparkles, targetSelector: "[data-testid='button-generate-ai']", position: "bottom-left", action: "Click to open the AI generator" },
  { id: "ai-prompt", title: "Describe Your Automation", description: "Type what you want your workflow to do. For example: 'When a new lead comes in, wait 5 minutes, then send an SMS, wait 1 day, then send a follow-up if they didn't reply.'", icon: Wand2, targetSelector: "[data-testid='input-ai-prompt']", position: "bottom-left", tip: "Be specific about timing, conditions, and actions for the best results." },
  { id: "add-steps", title: "Add Steps Manually", description: "Build workflows step by step. Choose from: Wait (time delays), SMS (send text messages), Condition (if/then logic), Alert (notify your team), and Code (custom scripts).", icon: Plus, position: "center", fallbackDescription: "Use the step buttons to add automation steps: Wait, SMS, Condition, Alert, and Code. Each step executes in sequence." },
  { id: "wait-step", title: "Wait Steps", description: "Add delays between actions. Set wait times in minutes or hours. Perfect for follow-up sequences — 'wait 1 hour, then check if they replied.'", icon: Clock, targetSelector: "[data-testid='button-add-step-wait']", position: "bottom-left" },
  { id: "sms-step", title: "SMS Steps", description: "Send automated text messages at any point in your workflow. Personalize with contact variables. Great for confirmations, reminders, and follow-ups.", icon: MessageCircle, targetSelector: "[data-testid='button-add-step-sms']", position: "bottom-left" },
  { id: "condition-step", title: "Condition Steps", description: "Add branching logic with if/then conditions. Route contacts down different paths based on their responses, tags, or engagement level.", icon: Filter, targetSelector: "[data-testid='button-add-step-condition']", position: "bottom-left" },
  { id: "publish", title: "Publish Your Workflow", description: "When your automation is ready, click 'Publish' to activate it. Published workflows run automatically when their trigger conditions are met.", icon: Rocket, targetSelector: "[data-testid='button-publish']", position: "top-right", action: "Click Publish to activate your workflow", fallbackDescription: "Once you build a workflow, the Publish button activates it. Published workflows run automatically in the background." },
  { id: "done", title: "Automation Master!", description: "You can now build any automation — from simple follow-up sequences to complex multi-branch workflows with AI. Start with the AI generator for the fastest results.", icon: CheckCircle2, position: "center" },
];

export const BOT_TRAINER_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to Neural Trainer", description: "Train your AI chatbot to understand your business. Feed it your website, set its personality, and deploy it as your 24/7 customer service agent.", icon: Brain, position: "center" },
  { id: "url-input", title: "Step 1: Enter Your Website URL", description: "Paste your business website URL. The AI will scrape and analyze every page, learning your services, pricing, team info, FAQs, and more.", icon: Globe, targetSelector: "[data-testid='input-training-url']", position: "bottom-left", tip: "Use your main website URL — the crawler will find all connected pages automatically." },
  { id: "persona", title: "Step 2: Set the Bot Persona", description: "Define how your AI assistant should behave. Set its name, tone, and personality. A dental office might use: 'Friendly receptionist named Sarah who helps with appointment booking.'", icon: Bot, targetSelector: "[data-testid='input-bot-persona']", position: "bottom-left", tip: "Be specific about tone — professional, casual, friendly, or authoritative." },
  { id: "train", title: "Step 3: Start Training", description: "Click 'Start Training' to begin. The AI scrapes your website, breaks content into knowledge chunks, generates embeddings, and builds a searchable knowledge base.", icon: Rocket, targetSelector: "[data-testid='button-start-training']", position: "bottom-left", action: "Click Start Training after entering your URL and persona" },
  { id: "progress", title: "Training Progress", description: "Watch the training progress in real-time. You'll see each step: crawling pages, extracting content, chunking text, generating embeddings, and indexing into the knowledge base.", icon: Database, position: "center", fallbackDescription: "Once training starts, a progress bar shows each phase: crawling, extraction, chunking, embedding, and indexing. Most sites train in under 2 minutes." },
  { id: "chat-test", title: "Step 4: Test Your Bot", description: "After training completes, test your bot in the chat panel. Ask it questions about your business — pricing, hours, services — and see how accurately it responds.", icon: TestTube, targetSelector: "[data-testid='input-bot-chat']", position: "bottom-left", fallbackDescription: "Once trained, a chat panel appears where you can ask your bot questions. Test it with real customer queries to see how it performs.", action: "Ask your bot a question about your business" },
  { id: "send-test", title: "Send Test Messages", description: "Type questions and click Send. The bot uses RAG (retrieval-augmented generation) to search its knowledge base and craft accurate, contextual responses.", icon: Send, targetSelector: "[data-testid='button-bot-send']", position: "bottom-left", fallbackDescription: "Use the Send button to test conversations. The bot retrieves relevant knowledge chunks and generates responses in real-time." },
  { id: "deploy", title: "Deploy Everywhere", description: "Your trained bot powers: the chat widget on your website, AI auto-replies in the Unified Inbox, and the Voice Agent's conversation intelligence.", icon: Zap, position: "center", tip: "Head to Website Integration to embed the chat widget on your live site." },
  { id: "done", title: "Bot Trained!", description: "Your AI assistant is ready. It will handle customer questions 24/7, route qualified leads to your inbox, and never miss a conversation. Retrain anytime to update its knowledge.", icon: CheckCircle2, position: "center" },
];

export const ONBOARDING_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to New Account Setup", description: "Create new sub-accounts for your clients in seconds. Each account gets its own inbox, workflows, bot, and branding — all managed from your agency dashboard.", icon: Briefcase, position: "center" },
  { id: "business-info", title: "Step 1: Business Information", description: "Enter your client's business name, industry, and contact details. This information populates their account profile and customizes their entire setup.", icon: Building, position: "center", tip: "The industry selection determines which blueprint template gets applied." },
  { id: "industry", title: "Step 2: Industry Selection", description: "Choose from 20+ industry blueprints: dental, medspa, law firm, gym, restaurant, real estate, and more. Each blueprint includes pre-built pipeline stages, custom fields, and message templates.", icon: Layers, position: "center" },
  { id: "blueprint", title: "Blueprint Preview", description: "Once you select an industry, the system previews the blueprint: pipeline stages (Lead → Booked → Won), custom fields for that vertical, and SMS/email templates. Everything is pre-configured.", icon: FileText, position: "center", fallbackDescription: "Blueprints auto-configure pipeline stages, custom fields, and message templates tailored to the chosen industry." },
  { id: "twilio", title: "Communication Setup", description: "Optionally assign a Twilio phone number to the new account. This enables SMS messaging, AI auto-replies, and voice agent capabilities right out of the box.", icon: Phone, position: "center", tip: "You can purchase new phone numbers in Voice Agent or assign existing ones." },
  { id: "provision", title: "Step 3: Create Account", description: "Hit Create and the system provisions everything: sub-account, pipeline, fields, templates, and notification settings. Your client is ready to go in under 10 seconds.", icon: Rocket, position: "center" },
  { id: "next-steps", title: "What's Next?", description: "After creating an account, head to: Neural Trainer to set up AI auto-replies, Voice Agent to deploy a phone agent, or Site Architect to build a website.", icon: Sparkles, position: "center" },
  { id: "done", title: "Ready to Onboard!", description: "You can now create accounts for any industry in seconds. Each account is fully independent with its own data, messaging, and AI configuration.", icon: CheckCircle2, position: "center" },
];

export const AD_LAUNCHER_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to Growth Engine", description: "Launch AI-powered ad campaigns in seconds. Describe your ideal campaign and the AI generates targeting, copy, creative concepts, and budget allocation.", icon: Megaphone, position: "center" },
  { id: "quick-prompts", title: "Quick Start Templates", description: "Choose from pre-built campaign prompts for common industries: Botox specials, gym memberships, dental cleanings. Click one to auto-fill the prompt with proven ad copy.", icon: Sparkles, targetSelector: "[data-testid='button-prompt-botox']", position: "bottom-left", tip: "Quick prompts are great starting points — customize them for your specific offer." },
  { id: "prompt", title: "Describe Your Campaign", description: "Type a detailed campaign description. Include: your offer, target audience, location, budget range, and goals. Example: '$50 teeth whitening special for adults 25-45 in Las Vegas, $500 budget.'", icon: Target, targetSelector: "[data-testid='input-ad-prompt']", position: "bottom-left" },
  { id: "generate", title: "Generate Campaign", description: "Click Generate to create your full campaign. The AI builds: ad headlines, body copy, audience targeting, budget allocation, estimated reach, and cost-per-lead projections.", icon: Rocket, targetSelector: "[data-testid='button-generate-campaign']", position: "bottom-left", action: "Click Generate after entering your campaign details" },
  { id: "preview", title: "Ad Preview", description: "See exactly how your ad will look before launching. The preview shows your headline, body copy, and creative placement in a realistic ad format.", icon: Image, targetSelector: "[data-testid='card-ad-preview']", position: "top-center", fallbackDescription: "After generating, a live ad preview card shows your headline, body copy, and creative — exactly how it would appear to potential customers." },
  { id: "budget", title: "Budget & Projections", description: "Review the AI's recommended daily budget, estimated reach, and projected cost per lead. These numbers are based on industry benchmarks for your targeting.", icon: DollarSign, targetSelector: "[data-testid='text-daily-budget']", position: "top-center", fallbackDescription: "The campaign dashboard shows your daily budget, estimated reach, and cost-per-lead projections based on industry benchmarks." },
  { id: "creative", title: "Upload Custom Creatives", description: "Upload your own ad images or use AI-generated creatives. High-quality visuals significantly boost click-through rates and engagement.", icon: Image, targetSelector: "[data-testid='button-upload-image']", position: "bottom-left", fallbackDescription: "You can upload custom ad images or let the AI generate visuals. The upload area appears below your ad preview." },
  { id: "strategy", title: "Strategy Notes", description: "The AI provides strategic recommendations: best posting times, audience insights, A/B testing suggestions, and optimization tips for your specific campaign.", icon: BarChart, targetSelector: "[data-testid='text-strategy-notes']", position: "top-center", fallbackDescription: "Each campaign includes AI-generated strategy notes with targeting recommendations, timing advice, and optimization tips." },
  { id: "launch", title: "Launch Campaign", description: "When everything looks right, click 'Launch Campaign' to go live. The system handles ad submission, budget allocation, and tracking setup automatically.", icon: Rocket, targetSelector: "[data-testid='button-launch-campaign']", position: "top-center", fallbackDescription: "The Launch button submits your campaign with all targeting, creative, and budget settings. One click to go live.", action: "Click Launch when your campaign is ready" },
  { id: "done", title: "Campaign Commander!", description: "You can now create and launch ad campaigns in under a minute. Use the AI generator for fast starts, then customize targeting and creatives for maximum impact.", icon: CheckCircle2, position: "center" },
];

export const VOICE_AGENT_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to Voice Agent", description: "Deploy AI-powered voice agents that can call leads, answer phones, book appointments, and handle objections — all with natural conversation. Build, train, and launch in minutes.", icon: Phone, position: "center" },
  { id: "describe", title: "Step 1: Describe Your Business", description: "Start by describing what your business does. This helps the AI generate a tailored persona, greeting, and objection-handling script.", icon: Briefcase, targetSelector: "[data-testid='input-business-description']", position: "bottom-left", tip: "Be specific about your services, target audience, and call goals." },
  { id: "examples", title: "Quick Start Examples", description: "Choose from pre-built examples: Med Spa, Gym, or Dental. Each fills in a proven persona with industry-specific objection handling and booking scripts.", icon: Sparkles, targetSelector: "[data-testid='button-example-medspa']", position: "bottom-left" },
  { id: "generate-persona", title: "Generate AI Persona", description: "Click 'Generate Persona' and the AI creates: agent name, personality description, opening greeting, and objection-handling rules tailored to your business.", icon: Wand2, targetSelector: "[data-testid='button-generate-persona']", position: "bottom-left", action: "Click Generate Persona to create your agent", fallbackDescription: "The Generate Persona button creates a complete voice agent profile with name, personality, greeting, and objection scripts." },
  { id: "edit-persona", title: "Customize Your Agent", description: "Fine-tune the agent's name, persona description, and first message. Edit the greeting to match your brand voice — professional, friendly, or energetic.", icon: Settings, targetSelector: "[data-testid='input-agent-name']", position: "bottom-left", fallbackDescription: "After generation, you can edit every detail: agent name, persona, greeting message, and objection rules." },
  { id: "objections", title: "Objection Handling", description: "Set up trigger phrases and AI responses for common objections. When a caller says 'too expensive,' your agent responds with a pre-crafted rebuttal. Add as many as you need.", icon: Shield, targetSelector: "[data-testid='button-add-objection']", position: "bottom-left", fallbackDescription: "The objection handler lets you define trigger phrases (e.g., 'too expensive') and craft AI responses for each one." },
  { id: "voice-select", title: "Choose a Voice", description: "Pick from multiple AI voices for your agent. Preview each one to hear the tone and style. Choose a voice that matches your brand personality.", icon: Mic, position: "center", fallbackDescription: "Select from AI voices with different tones — professional, warm, energetic. Preview each before deploying." },
  { id: "deploy", title: "Deploy Agent", description: "Click 'Deploy Agent' to activate. Your voice agent goes live instantly — ready to handle inbound calls and make outbound calls to your leads.", icon: Rocket, targetSelector: "[data-testid='button-deploy-agent']", position: "top-center", action: "Click Deploy to launch your voice agent", fallbackDescription: "The Deploy button activates your agent on Vapi's infrastructure. Once deployed, it can handle calls immediately." },
  { id: "demo-call", title: "Test with Demo Call", description: "Try a live demo call right in your browser. Click 'Demo' on any deployed agent to have a real-time voice conversation and hear how it performs.", icon: Headphones, position: "center", fallbackDescription: "After deploying, use the Demo button to start a browser-based voice call with your agent. Test the conversation flow live." },
  { id: "outbound", title: "Make Outbound Calls", description: "Enter a phone number and click Call to have your agent dial leads automatically. The agent handles the full conversation — greeting, pitch, objection handling, and booking.", icon: PhoneCall, position: "center", fallbackDescription: "Use the outbound calling panel to dial leads. Enter a phone number and your agent makes the call with its trained persona." },
  { id: "phone-numbers", title: "Phone Number Management", description: "Search and purchase dedicated phone numbers by area code. Bought numbers automatically link to your voice agent for caller ID on outbound calls.", icon: Hash, targetSelector: "[data-testid='input-area-code']", position: "bottom-left", fallbackDescription: "The phone number section lets you search by area code, purchase numbers, and auto-link them to your voice agent." },
  { id: "done", title: "Voice Agent Deployed!", description: "Your AI voice agent is live and ready. It handles calls 24/7, overcomes objections, books appointments, and never takes a break. Scale by deploying multiple agents for different campaigns.", icon: CheckCircle2, position: "center" },
];

export const GROWTH_CENTER_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to Growth Center", description: "Your power dialer command center. Load lead lists, connect your voice agent, and blast through outbound calls at scale — automatically.", icon: TrendingUp, position: "center" },
  { id: "select-agent", title: "Step 1: Select Your Agent", description: "Choose which deployed voice agent will make the calls. Each agent has its own persona, script, and objection handling — pick the one that matches your campaign.", icon: Bot, targetSelector: "[data-testid='input-assistant-id']", position: "bottom-left", fallbackDescription: "The agent selector dropdown shows all your deployed voice agents. Choose the one trained for this campaign." },
  { id: "phone-id", title: "Set Caller ID", description: "Enter your Vapi Phone Number ID for outbound caller ID. Leads see a local number, which dramatically increases answer rates.", icon: Phone, targetSelector: "[data-testid='input-dialer-phone-id']", position: "bottom-left" },
  { id: "add-leads", title: "Step 2: Load Your Leads", description: "Add leads one by one or paste a list. Each lead needs a name and phone number. The dialer calls them in order, with your AI agent handling each conversation.", icon: UserPlus, targetSelector: "[data-testid='button-add-lead']", position: "bottom-left", action: "Click Add Lead to start building your call list" },
  { id: "lead-details", title: "Lead Information", description: "For each lead, enter their name and phone number. The AI agent uses the name for personalized greetings — 'Hi Sarah, this is...' instead of generic cold-call openers.", icon: Users, position: "center", fallbackDescription: "Fill in each lead's name and number. The AI personalizes greetings using their name for higher engagement." },
  { id: "start-dialing", title: "Step 3: Start Power Dialer", description: "Hit 'Start Power Dialer' to begin the automated calling campaign. Your voice agent calls each lead sequentially, logs results, and moves to the next.", icon: Zap, targetSelector: "[data-testid='button-start-power-dialer']", position: "bottom-left", action: "Click Start when your lead list is ready", fallbackDescription: "The Start button launches the automated calling campaign. Your agent calls leads one by one with its trained persona." },
  { id: "results", title: "Live Results Dashboard", description: "Watch call results stream in real-time. See which leads answered, call duration, and outcomes. The dashboard tracks your pick-up rate and conversion metrics.", icon: BarChart, position: "center", fallbackDescription: "As calls complete, results appear with status badges: completed, no answer, voicemail. Track your campaign's pick-up rate live." },
  { id: "done", title: "Dialer Ready!", description: "You can now blast through hundreds of outbound calls with AI handling every conversation. Load your leads, pick your agent, and let the machine work.", icon: CheckCircle2, position: "center" },
];

export const REPUTATION_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to Reputation Manager", description: "Monitor, manage, and respond to customer reviews in one place. Generate AI-powered responses, track your rating score, and boost your online reputation.", icon: Star, position: "center" },
  { id: "stats", title: "Reputation Dashboard", description: "See your key metrics at a glance: total reviews, average rating, response rate, and positive review percentage. Track how your reputation changes over time.", icon: BarChart, position: "center", fallbackDescription: "The stats row shows total reviews, average rating, response rate, and positive sentiment percentage across all platforms." },
  { id: "google-link", title: "Google Review Link", description: "Enter your Google Business review link. This lets your customers leave reviews directly on Google, boosting your local SEO and visibility.", icon: Link, targetSelector: "[data-testid='input-google-review-link']", position: "bottom-left", tip: "Find your Google review link in Google Business Profile → Share review form." },
  { id: "review-link", title: "Shareable Review Link", description: "Copy your custom review collection link and share it with customers via SMS, email, or QR code. Every review submitted here feeds into your dashboard.", icon: Copy, targetSelector: "[data-testid='input-review-link']", position: "bottom-left", fallbackDescription: "Your unique review collection URL can be shared via text, email, or printed QR code to collect customer feedback." },
  { id: "review-cards", title: "Review Feed", description: "Browse all your customer reviews in a scrollable feed. Each card shows the reviewer name, star rating, comment, and whether it's been responded to.", icon: MessageCircle, position: "center", fallbackDescription: "Reviews appear as cards with customer name, rating, comment, date, and response status. New reviews appear at the top." },
  { id: "ai-response", title: "AI Response Generator", description: "Click 'Generate AI Response' on any review to create a professional, personalized reply. The AI matches your brand tone and addresses specific feedback points.", icon: Sparkles, position: "center", tip: "AI responses work for both positive and negative reviews — grateful for 5-star, empathetic for low ratings." },
  { id: "visibility", title: "Public/Private Toggle", description: "Control which reviews are publicly visible. Toggle reviews on or off to curate your public review page. Hidden reviews still show in your dashboard.", icon: Eye, position: "center" },
  { id: "alerts", title: "Negative Review Alerts", description: "When a low-rated review comes in, the system can alert you immediately via SMS or push notification so you can respond quickly and prevent reputation damage.", icon: Bell, position: "center", tip: "Responding within 1 hour to negative reviews shows customers you care and can turn critics into advocates." },
  { id: "done", title: "Reputation Protected!", description: "You're now equipped to manage your online reputation proactively. Collect reviews, respond with AI, and monitor your rating — all from one dashboard.", icon: CheckCircle2, position: "center" },
];

export const SENTINEL_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to Apex Sentinel", description: "Real-time accident and incident scanner for personal injury law firms. Monitor live police and traffic feeds, detect incidents in your target areas, and deploy geofenced ads instantly.", icon: Satellite, position: "center" },
  { id: "stats", title: "Incident Dashboard", description: "Four key metrics: Total Incidents detected, Critical severity count, Pending Actions awaiting response, and Actioned incidents you've already handled.", icon: BarChart, targetSelector: "[data-testid='card-total-incidents']", position: "bottom-left" },
  { id: "config", title: "Scanner Configuration", description: "Open Settings to configure your scanner: feed URLs (LVMPD, FL Highway Patrol), target keywords, cities, states, scan interval, and geofence radius.", icon: Settings, targetSelector: "[data-testid='button-sentinel-config']", position: "bottom-left", action: "Click to open scanner settings" },
  { id: "feed-url", title: "Live Feed Sources", description: "Configure RSS/API feed URLs for live incident data. The system supports LVMPD (Nevada) and Florida Highway Patrol feeds. Each feed is scraped and parsed in real-time.", icon: Radio, targetSelector: "[data-testid='input-feed-url']", position: "bottom-left", fallbackDescription: "In settings, you can configure live feed URLs for police and traffic data sources. Currently supports LVMPD and FL FHP." },
  { id: "keywords", title: "Keyword Targeting", description: "Set keywords to filter incidents: 'accident, crash, injury, collision, DUI.' Only incidents matching your keywords appear in the feed, filtering out noise.", icon: Filter, targetSelector: "[data-testid='input-keywords']", position: "bottom-left", fallbackDescription: "Keyword filters narrow the feed to relevant incidents — accidents, crashes, injuries. Customize for your practice area." },
  { id: "location", title: "Location Targeting", description: "Specify target cities and states. Only incidents in your licensed practice areas are shown. Perfect for multi-state firms or firms focused on specific metro areas.", icon: MapPin, targetSelector: "[data-testid='input-target-cities']", position: "bottom-left", fallbackDescription: "Location targeting filters incidents to your practice areas. Enter cities and states where you're licensed to operate." },
  { id: "scan", title: "Trigger Manual Scan", description: "Click 'Scan Now' to immediately pull the latest incidents from all configured feeds. The scanner parses, deduplicates, and classifies each incident by severity.", icon: ScanSearch, targetSelector: "[data-testid='button-scan-now']", position: "bottom-left", action: "Click Scan Now to fetch live incidents" },
  { id: "live-stream", title: "Live Incident Feed", description: "Incidents appear in real-time with severity badges (Critical, High, Medium), source tags (LVMPD, FL FHP), location, and timestamp. Most recent incidents at the top.", icon: AlertTriangle, targetSelector: "[data-testid='text-live-stream-title']", position: "bottom-left", fallbackDescription: "The live feed shows detected incidents with severity, source, location, and time. Critical incidents are flagged in red." },
  { id: "filter", title: "Location Filter", description: "Use the search box above the feed to filter incidents by location. Type a city name or intersection to find specific incidents quickly.", icon: Search, targetSelector: "[data-testid='input-location-filter']", position: "bottom-left", fallbackDescription: "The search box filters the incident feed by location — type a city or street name to narrow results." },
  { id: "geofence", title: "Deploy Geofenced Ads", description: "Click 'Geofence' on any incident to instantly deploy targeted ads in a radius around the accident location. Reach potential clients who witnessed or were involved in the incident.", icon: Target, position: "center", tip: "Geofenced ads reach people within your configured radius of the incident — typically 1-5 miles." },
  { id: "sms-alert", title: "SMS Notifications", description: "Click 'SMS' on any incident to immediately text your account owner about the incident. Instant alerts mean faster response times for time-sensitive cases.", icon: Bell, position: "center" },
  { id: "acknowledge", title: "Acknowledge & Track", description: "Mark incidents as 'Acknowledged' after you've taken action. This moves them from Pending to Actioned, keeping your dashboard clean and audit-ready.", icon: CheckCircle2, position: "center" },
  { id: "done", title: "Sentinel Active!", description: "You're now monitoring live incident feeds across your target areas. Configure your scan interval for automated monitoring, and deploy geofenced ads the moment accidents happen.", icon: CheckCircle2, position: "center" },
];

export const PROPERTY_RADAR_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to Property Radar", description: "Find distressed properties and motivated sellers in real-time. Scan zip codes for pre-foreclosure, absentee owner, and high-equity opportunities — then reach out instantly.", icon: Home, position: "center" },
  { id: "views", title: "Feed & Pipeline Views", description: "Toggle between Feed view (all leads as cards) and Pipeline view (kanban-style deal stages). Use Feed for discovery, Pipeline for tracking active deals.", icon: Columns, targetSelector: "[data-testid='button-view-feed']", position: "bottom-left" },
  { id: "stats", title: "Key Metrics", description: "Track Total Leads, Hot Leads (high distress), Total Equity across all properties, and Potential Profit from your pipeline. These update with every scan.", icon: BarChart, targetSelector: "[data-testid='text-total-leads']", position: "bottom-left" },
  { id: "config", title: "Scanner Configuration", description: "Open Settings to configure: target zip codes, cities, distress signal types (Pre-Foreclosure, Absentee Owner, High Equity), minimum equity threshold, and auto-outreach toggles.", icon: Settings, targetSelector: "[data-testid='button-config']", position: "bottom-left", action: "Click Settings to configure your search" },
  { id: "zip-codes", title: "Target Zip Codes", description: "Enter the zip codes you want to scan for properties. The system queries real property databases and cross-references with public records for distress signals.", icon: MapPin, targetSelector: "[data-testid='input-target-zips']", position: "bottom-left", fallbackDescription: "In settings, enter target zip codes separated by commas. The scanner queries real property databases for each zip." },
  { id: "distress", title: "Distress Signal Filters", description: "Choose which distress types to track: Pre-Foreclosure (behind on payments), Absentee Owner (not living at property), High Equity (50%+ equity). Each signals a motivated seller.", icon: AlertTriangle, targetSelector: "[data-testid='input-distress-filters']", position: "bottom-left", fallbackDescription: "Filter by distress type: Pre-Foreclosure, Absentee Owner, or High Equity. Each indicates a different seller motivation." },
  { id: "auto-outreach", title: "Automated Outreach", description: "Enable auto-SMS, auto-call, or auto-ads to reach property owners immediately when a new distressed property is detected. First-mover advantage wins deals.", icon: Zap, targetSelector: "[data-testid='switch-auto-sms']", position: "bottom-left", fallbackDescription: "Toggle on auto-SMS, auto-call, or auto-ads to automatically reach out to property owners when new leads are detected.", tip: "First contact within 5 minutes of detection dramatically increases conversion." },
  { id: "scan", title: "Run Property Scan", description: "Click 'Scan' to search your target areas for distressed properties. Results come from live property data and are classified by distress type and severity.", icon: ScanSearch, targetSelector: "[data-testid='button-scan']", position: "bottom-left", action: "Click Scan to find properties" },
  { id: "lead-cards", title: "Property Lead Cards", description: "Each property appears as a detailed card showing: address, estimated value, equity amount, distress type, and action buttons for SMS, ads, and pipeline stage changes.", icon: Home, position: "center", fallbackDescription: "Property leads display as cards with address, value, equity, distress type, and one-click action buttons for outreach." },
  { id: "pipeline", title: "Pipeline Management", description: "Move leads through stages: New → Contacted → Negotiating → Under Contract → Closed. Track every property from discovery to closing, with full history.", icon: Layers, targetSelector: "[data-testid='button-view-pipeline']", position: "bottom-left" },
  { id: "done", title: "Radar Active!", description: "You're ready to find distressed properties and close deals. Set up auto-outreach for instant contact, and check your pipeline daily to move deals forward.", icon: CheckCircle2, position: "center" },
];

export const WEBSITE_INTEGRATION_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to Website Integration", description: "Add websites, train AI chatbots on their content, embed chat widgets via a JavaScript snippet, and verify installations — all from one control center.", icon: Globe, position: "center" },
  { id: "add-site", title: "Step 1: Add a Website", description: "Click 'Add Website' to register a new site. Enter the name and URL. The site starts in draft status — no DNS or domain changes are required.", icon: Plus, targetSelector: "[data-testid='button-add-website']", position: "bottom-left", action: "Click to add your first website", fallbackDescription: "The Add Website button opens a dialog where you enter the site name and URL. No DNS or domain setup is needed — this integration works via a JS embed snippet." },
  { id: "site-cards", title: "Your Websites", description: "Each website appears as a card showing: name, URL, current status (draft, training, trained, verified), and content block count. Click any card to manage it.", icon: Layers, position: "center", fallbackDescription: "Your websites appear as cards in a list. Each shows the site name, URL, training status, and widget state. Statuses reflect real, verified conditions." },
  { id: "train-bot", title: "Step 2: Train the AI", description: "Click 'Scrape & Train' to scrape the website and build an AI knowledge base. The system extracts real content blocks (headings, paragraphs, lists) and reports exact counts — no fake metrics.", icon: Brain, targetSelector: "[data-testid='button-train-bot']", position: "bottom-left", fallbackDescription: "The training button scrapes the website content and builds a real AI knowledge base. If scraping fails, you'll see the specific error and reason.", action: "Click to start AI training" },
  { id: "widget-config", title: "Step 3: Configure the Widget", description: "Customize the chat widget: set the accent color, choose position (bottom-right or bottom-left), and write a greeting message.", icon: Settings, targetSelector: "[data-testid='input-widget-color']", position: "bottom-left", fallbackDescription: "The widget configuration panel lets you set color, position, greeting, and enable/disable the chat widget." },
  { id: "widget-position", title: "Widget Position", description: "Choose where the chat bubble appears on the website: bottom-right (most common) or bottom-left.", icon: Columns, targetSelector: "[data-testid='select-widget-position']", position: "bottom-left", fallbackDescription: "Position the chat widget on either the bottom-right or bottom-left corner of the website." },
  { id: "widget-greeting", title: "Custom Greeting", description: "Set the initial message visitors see when the chat widget opens. A good greeting is friendly and action-oriented: 'Hi! How can I help you today?'", icon: MessageCircle, targetSelector: "[data-testid='input-widget-greeting']", position: "bottom-left", fallbackDescription: "The greeting message is the first thing visitors see when they open the chat. Make it welcoming and helpful." },
  { id: "embed-code", title: "Step 4: Get the Embed Code", description: "Click 'Generate Embed Code' to get the JavaScript snippet. Copy it and paste it before the closing </body> tag on the website.", icon: Code, targetSelector: "[data-testid='button-generate-embed']", position: "bottom-left", fallbackDescription: "The embed code generator creates a ready-to-paste JS snippet. Add it to any website — no DNS or domain changes needed.", action: "Click to generate the embed snippet" },
  { id: "verify", title: "Step 5: Verify Installation", description: "After placing the embed code, click 'Verify Installation' in the Manage tab. The system checks whether the widget script is actually present on the site. Only a successful verification marks the site as live.", icon: Shield, targetSelector: "[data-testid='button-verify-install']", position: "bottom-left", fallbackDescription: "The Verify Installation button fetches the website and checks for the widget script. If not found, you'll see a specific reason and next steps." },
  { id: "preview", title: "Live Site Preview", description: "Preview the website directly in the platform. See how the site looks and verify the chat widget placement without leaving your dashboard.", icon: Eye, targetSelector: "[data-testid='iframe-site-preview']", position: "top-center", fallbackDescription: "The site preview panel shows a live iframe of the website, so you can verify everything looks correct." },
  { id: "done", title: "You're All Set!", description: "Your website now has an AI-powered chat widget trained on its content. Visitors get instant, accurate answers 24/7. Re-train anytime to update the knowledge base.", icon: CheckCircle2, position: "center" },
];

export const FORM_BUILDER_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to AI Form Builder", description: "Generate professional, industry-compliant forms in seconds with AI. Just select your industry and business name — the AI creates all fields, validation, and compliance notes.", icon: FormInput, position: "center" },
  { id: "tabs", title: "Four-Step Process", description: "Form Builder has four tabs: Generate (AI creation), Edit (customize fields), Preview (see the final form), and Embed (get the code). Follow them left to right.", icon: Layers, position: "center" },
  { id: "industry", title: "Step 1: Select Industry", description: "Choose your industry from the dropdown or type to search. Options include Medical, Dental, Legal, Fitness, Real Estate, Restaurant, and more. The AI uses this to generate compliant fields.", icon: Building, targetSelector: "[data-testid='input-industry']", position: "bottom-left", tip: "Each industry has specific compliance requirements (HIPAA for medical, informed consent for dental, etc.)." },
  { id: "quick-industries", title: "Quick Industry Select", description: "Click any industry badge to instantly fill in the selection. Common industries are pre-loaded for one-click access.", icon: Zap, position: "center", fallbackDescription: "Industry badges below the dropdown let you select common industries with one click." },
  { id: "business-name", title: "Your Business Name", description: "Enter your business name. It appears in the form header, submission confirmation, and compliance footer. Make it match your official business name.", icon: Building, targetSelector: "[data-testid='input-business-name']", position: "bottom-left" },
  { id: "generate", title: "Generate Form", description: "Click 'Generate Form with AI' and the system creates a complete form with all relevant fields, proper validation, placeholder text, and industry-specific compliance notes.", icon: Sparkles, targetSelector: "[data-testid='button-generate-form']", position: "bottom-left", action: "Click Generate to create your form" },
  { id: "edit-fields", title: "Step 2: Edit Fields", description: "Switch to the Edit tab to customize every field: change labels, types (text, email, phone, select, checkbox), placeholders, help text, and required/optional status.", icon: Settings, targetSelector: "[data-testid='tab-edit']", position: "bottom-left", fallbackDescription: "The Edit tab lets you modify every field — change labels, types, placeholders, validation, and ordering." },
  { id: "field-types", title: "Field Types", description: "Choose from: Text, Email, Phone, Textarea, Select (dropdown), Checkbox, Date, and Number. Each type includes automatic validation and formatting.", icon: Type, position: "center" },
  { id: "reorder", title: "Reorder Fields", description: "Use the up/down arrows to reorder fields. Put the most important fields first — name, contact info, then specific details. Good order improves completion rates.", icon: ArrowUpDown, position: "center", tip: "Forms with 5-7 fields get 20% more completions than longer forms." },
  { id: "add-field", title: "Add Custom Fields", description: "Click 'Add Field' to create custom fields beyond what the AI generated. Add anything: appointment preferences, insurance info, referral sources, and more.", icon: Plus, targetSelector: "[data-testid='button-add-field']", position: "bottom-left", fallbackDescription: "The Add Field button lets you create custom fields on top of the AI-generated ones." },
  { id: "preview", title: "Step 3: Preview", description: "Switch to the Preview tab to see your form exactly as it will appear to visitors. Test the layout, check mobile responsiveness, and verify all fields are correct.", icon: Eye, targetSelector: "[data-testid='tab-preview']", position: "bottom-left", fallbackDescription: "The Preview tab shows a live rendering of your form with all styling, validation, and compliance notes." },
  { id: "embed", title: "Step 4: Embed", description: "Switch to the Embed tab to get the HTML code. Copy and paste it into any website to deploy the form. The code includes styling, validation, and submission handling.", icon: Code, targetSelector: "[data-testid='tab-embed']", position: "bottom-left", fallbackDescription: "The Embed tab provides ready-to-paste HTML code that includes the form, styling, and submission handling." },
  { id: "done", title: "Form Ready!", description: "Your AI-generated form is ready to embed on any website. It includes industry-compliant fields, proper validation, and a professional design. Generate forms for any industry in seconds.", icon: CheckCircle2, position: "center" },
];

export const COMMAND_CENTER_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to Command Center", description: "Your agency war room. Monitor all sub-accounts, track revenue, leads, and messages across your entire portfolio from one high-level dashboard.", icon: Command, position: "center" },
  { id: "revenue", title: "Total Revenue", description: "See your combined revenue across all sub-accounts. This aggregates subscription fees, usage charges, and any additional billing from all your managed accounts.", icon: DollarSign, targetSelector: "[data-testid='card-total-revenue']", position: "bottom-left" },
  { id: "accounts", title: "Active Accounts", description: "Total number of sub-accounts in your portfolio. Each account represents a client business you're managing through the platform.", icon: Users, targetSelector: "[data-testid='card-total-accounts']", position: "bottom-left" },
  { id: "leads", title: "Total Leads", description: "Combined lead count across all accounts. Track how many potential customers your clients are attracting through their campaigns and automations.", icon: Target, targetSelector: "[data-testid='card-total-leads']", position: "bottom-left" },
  { id: "messages", title: "Total Messages", description: "Message volume across your entire fleet. Monitor communication activity to spot accounts that need attention or are scaling quickly.", icon: MessageSquare, targetSelector: "[data-testid='card-total-messages']", position: "bottom-left" },
  { id: "fleet", title: "Fleet Health Monitor", description: "The production pipeline visualization shows the health and status of every sub-account. Spot underperforming accounts, identify growth trends, and prioritize your attention.", icon: PieChart, position: "center", fallbackDescription: "The fleet view shows all your accounts with health indicators — helping you spot which clients need attention." },
  { id: "bulk-rollback", title: "Bulk Rollback", description: "Roll back multiple accounts to a previous snapshot version simultaneously. Essential for agencies that need to undo changes across their entire fleet.", icon: History, targetSelector: "[data-testid='button-bulk-rollback']", position: "bottom-left", fallbackDescription: "The Bulk Rollback tool lets you revert multiple accounts to a saved snapshot version in one action." },
  { id: "done", title: "Command Center Active!", description: "You now have full visibility across your agency. Use this dashboard daily to monitor account health, track growth metrics, and manage your client portfolio.", icon: CheckCircle2, position: "center" },
];

export const SNAPSHOTS_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to Snapshot Manager", description: "Save, version, and rollback your account configurations. Create checkpoints before making changes, and restore any previous version with one click.", icon: Camera, position: "center" },
  { id: "create-checkpoint", title: "Step 1: Save a Checkpoint", description: "Enter a descriptive name for your checkpoint and click Save. This captures your current account state: pipelines, fields, templates, bot configuration, and settings.", icon: Save, targetSelector: "[data-testid='input-checkpoint-name']", position: "bottom-left", tip: "Name checkpoints clearly: 'Before holiday campaign update' or 'v2.1 pipeline changes'." },
  { id: "save", title: "Save Checkpoint", description: "Click Save to create the checkpoint. Every save is timestamped and stored permanently. You can create unlimited checkpoints for version tracking.", icon: Download, targetSelector: "[data-testid='button-save-checkpoint']", position: "bottom-left", action: "Click Save after naming your checkpoint" },
  { id: "version-list", title: "Version History", description: "Browse all your saved checkpoints in reverse chronological order. Each version shows the name, creation date, and a Rollback button to restore it.", icon: History, position: "center", fallbackDescription: "Your checkpoint history appears as a list of version cards with names, dates, and restore buttons." },
  { id: "rollback", title: "Rollback to Previous Version", description: "Click 'Rollback' on any version to restore your account to that exact state. This is non-destructive — your current state is automatically checkpointed before rollback.", icon: History, position: "center", tip: "Always save a checkpoint of your current state before rolling back — just in case." },
  { id: "publish", title: "Publish to Marketplace", description: "Click 'Publish Snapshot' to share your configuration as a template in the Marketplace. Set a name, description, and price — other agencies can buy and fork your setup.", icon: Upload, targetSelector: "[data-testid='button-publish-snapshot']", position: "bottom-left", action: "Click to publish your configuration as a template" },
  { id: "publish-details", title: "Publish Details", description: "Set a marketplace name, detailed description, and price for your snapshot. Free snapshots attract more installs; paid snapshots generate passive revenue.", icon: Tag, position: "center", fallbackDescription: "When publishing, set a name, description, and optional price. Published snapshots appear in the Marketplace for other agencies." },
  { id: "done", title: "Version Control Ready!", description: "You now have full version control for your account configurations. Save checkpoints before changes, rollback if needed, and publish your best setups as marketplace templates.", icon: CheckCircle2, position: "center" },
];

export const MARKETPLACE_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to Snapshot Marketplace", description: "Browse and install pre-built account configurations from other agencies. Find industry-specific setups with pipelines, templates, and workflows — ready to use in one click.", icon: ShoppingBag, position: "center" },
  { id: "search", title: "Search Snapshots", description: "Use the search bar to find snapshots by name, industry, or feature. Search for 'dental' to find dental office configurations, or 'gym' for fitness studio setups.", icon: Search, targetSelector: "[data-testid='input-marketplace-search']", position: "bottom-left" },
  { id: "filters", title: "Industry Filters", description: "Click industry filter badges to narrow results. Browse by vertical: Dental, Legal, Fitness, Real Estate, Restaurant, Med Spa, and more.", icon: Filter, position: "center", fallbackDescription: "Industry filter badges let you browse snapshots by vertical — click one to see only templates for that industry." },
  { id: "snapshot-cards", title: "Snapshot Details", description: "Each snapshot card shows: name, description, industry tag, creator, rating, price (free or paid), and an Install button. Preview before installing.", icon: FileText, position: "center", fallbackDescription: "Snapshots appear as cards with name, description, creator info, rating, and price. Click Install to add one to your account." },
  { id: "install", title: "Install a Snapshot", description: "Click 'Install' to fork the snapshot into your account. You'll be asked to enter a business name — the snapshot's configuration will be applied to a new sub-account.", icon: Download, position: "center", tip: "Installing a snapshot creates a new sub-account with the template's configuration pre-applied." },
  { id: "fork", title: "Fork & Customize", description: "After installing, the snapshot becomes fully yours. Customize the pipelines, templates, and settings to match your specific client. It's a starting point, not a locked template.", icon: GitFork, position: "center" },
  { id: "done", title: "Marketplace Explorer!", description: "You can now discover and install proven business configurations. Install a snapshot, customize it for your client, and save hours of manual setup.", icon: CheckCircle2, position: "center" },
];

export const AFFILIATE_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to Affiliate Dashboard", description: "Earn commissions by referring new agencies to the platform. Share your unique referral link, track sign-ups, and watch your earnings grow with tiered commission rates.", icon: Share2, position: "center" },
  { id: "commissions", title: "Monthly Commissions", description: "See your current month's commission earnings. Commissions are calculated from active subscriptions referred through your link, with tiered rates from 30% to 50%.", icon: DollarSign, targetSelector: "[data-testid='card-monthly-commissions']", position: "bottom-left" },
  { id: "referrals", title: "Referral Count", description: "Track how many agencies have signed up through your referral link. Each active referral generates recurring monthly commissions for the life of their subscription.", icon: Users, targetSelector: "[data-testid='card-referral-count']", position: "bottom-left" },
  { id: "total-earned", title: "Total Earned", description: "Your all-time earnings from the affiliate program. Commissions accrue monthly and are paid out on a regular schedule.", icon: Banknote, targetSelector: "[data-testid='card-total-earned']", position: "bottom-left" },
  { id: "referral-link", title: "Your Referral Link", description: "Copy your unique referral link and share it anywhere — social media, emails, blog posts, YouTube descriptions. Every sign-up through this link earns you commissions.", icon: Link, targetSelector: "[data-testid='input-referral-link']", position: "bottom-left", action: "Click Copy to get your referral link" },
  { id: "copy-link", title: "Share & Earn", description: "Click Copy to grab your link. Share it in: Facebook groups, agency communities, YouTube tutorials, email signatures, and client onboarding materials.", icon: Copy, targetSelector: "[data-testid='button-copy-link']", position: "bottom-left", tip: "Top affiliates share their link in value-first content — tutorials, case studies, and reviews." },
  { id: "tiers", title: "Commission Tiers", description: "Earn 30% on your first 10 referrals, 40% on referrals 11-50, and 50% on all referrals beyond 50. The more you refer, the higher your earning rate on ALL referrals.", icon: Percent, position: "center" },
  { id: "done", title: "Affiliate Ready!", description: "Start sharing your referral link to earn recurring commissions. Every agency that signs up through your link generates passive income for you month after month.", icon: CheckCircle2, position: "center" },
];

export const GOD_MODE_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to God Mode", description: "One-click empire builder. Enter a business name, pick an industry, and God Mode provisions EVERYTHING: sub-account, phone number, voice agent, AI bot, website, and automated workflows.", icon: Bolt, position: "center" },
  { id: "business-name", title: "Step 1: Business Name", description: "Enter the name of the business you're setting up. This becomes the sub-account name and is used across all generated assets — website, voicemail greeting, and email templates.", icon: Building, targetSelector: "[data-testid='input-business-name']", position: "bottom-left" },
  { id: "industry", title: "Step 2: Select Industry", description: "Pick the business industry. God Mode uses this to select the right blueprint, generate industry-specific content, and configure the voice agent with relevant scripts.", icon: Layers, position: "center", fallbackDescription: "Choose from available industry options. Each industry gets a tailored setup with specific templates, pipeline stages, and AI training." },
  { id: "website", title: "Website URL (Optional)", description: "If the business has a website, enter it here. God Mode will scrape it to train the AI bot, ensuring the chatbot knows the business's specific services, pricing, and details.", icon: Globe, targetSelector: "[data-testid='input-website']", position: "bottom-left", tip: "Providing a website URL makes the AI bot dramatically smarter about the specific business." },
  { id: "area-code", title: "Phone Area Code", description: "Enter the preferred area code for the business phone number. God Mode will search for and purchase an available number in that area code from Twilio.", icon: Phone, targetSelector: "[data-testid='input-area-code']", position: "bottom-left" },
  { id: "launch", title: "Launch God Mode", description: "Click the launch button and watch the magic happen. God Mode executes 6+ operations in sequence: account creation, phone provisioning, voice agent deployment, bot training, site generation, and workflow setup.", icon: Rocket, targetSelector: "[data-testid='button-launch-god-mode']", position: "bottom-left", action: "Click Launch to build the entire business setup" },
  { id: "progress", title: "Build Progress", description: "Watch each step complete in real-time with animated progress indicators. Each phase shows its status: pending, in-progress, complete, or failed. The full build takes about 30-60 seconds.", icon: Play, position: "center", fallbackDescription: "During the build, animated step indicators show progress through each phase. Watch as the entire business infrastructure materializes." },
  { id: "results", title: "Launch Results", description: "When complete, you'll see links to every created asset: sub-account dashboard, voice agent, trained bot, generated website, and active workflows. Everything is live and ready.", icon: CheckCircle2, position: "center", fallbackDescription: "After completion, God Mode displays links to all created assets: dashboard, voice agent, AI bot, website, and workflows." },
  { id: "reset", title: "Build Another", description: "Click 'Build Another Empire' to reset and create another business from scratch. Each God Mode run creates a completely independent sub-account with its own infrastructure.", icon: Rocket, targetSelector: "[data-testid='button-reset-god-mode']", position: "bottom-left", fallbackDescription: "The reset button clears the form so you can build another business setup from scratch." },
  { id: "done", title: "Empire Builder!", description: "You've unlocked the fastest way to launch a complete business presence. One form, one click, and everything is live — phone, AI, website, and automation. Build unlimited empires.", icon: Bolt, position: "center" },
];

export const DOMAINS_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to Domain Manager", description: "Search, purchase, and manage custom domains for your client websites. Connect domains to your generated sites for professional, branded URLs.", icon: Globe, position: "center" },
  { id: "search", title: "Step 1: Search for a Domain", description: "Type your desired domain name in the search bar. The system checks availability across multiple TLDs (.com, .io, .ai, .co, .app, .dev, .net, .org) instantly.", icon: Search, targetSelector: "[data-testid='input-domain-search']", position: "bottom-left", tip: "Try your business name first, then get creative with .io or .ai extensions if .com is taken." },
  { id: "tld-select", title: "Choose Your Extension", description: "Select a TLD from the dropdown. Each extension has different pricing — .com is most popular, .ai is trendy for tech businesses, .io works great for startups.", icon: Globe, targetSelector: "[data-testid='select-tld']", position: "bottom-left" },
  { id: "check", title: "Check Availability", description: "Click Search to check if your domain is available. You'll see the result instantly — available (green check) or taken (red X) — along with the price.", icon: ShoppingCart, targetSelector: "[data-testid='button-search-domain']", position: "bottom-left", action: "Click Search after entering your domain" },
  { id: "results", title: "Domain Results", description: "See availability results with pricing for your primary domain, plus alternative TLD options. Compare prices and find the best option for your brand.", icon: CheckCircle2, targetSelector: "[data-testid='domain-check-result']", position: "bottom-left", fallbackDescription: "After searching, results show availability, pricing, and a Buy button for available domains. Alternative TLDs are listed below." },
  { id: "buy", title: "Step 2: Purchase Domain", description: "Click 'Buy Now' on any available domain to purchase it. The domain is registered and linked to your sub-account automatically.", icon: ShoppingCart, position: "center", fallbackDescription: "Click the Buy button next to any available domain. It's registered instantly and linked to your account." },
  { id: "active-domains", title: "Your Domains", description: "All purchased domains appear in the 'Active Domains' section below. See the status, linked site, and DNS/SSL configuration for each domain.", icon: Lock, targetSelector: "[data-testid='active-domains-card']", position: "top-center", fallbackDescription: "Your purchased domains appear in the Active Domains section with status, linked site, and DNS/SSL settings." },
  { id: "connect-site", title: "Connect to a Website", description: "Link a domain to any site you've built in Site Architect. Once connected, your generated website is accessible at that domain with automatic SSL.", icon: Link, position: "center", tip: "SSL certificates are configured automatically — your site is secure from day one." },
  { id: "done", title: "Domain Expert!", description: "You can now search, purchase, and manage domains for all your client websites. Every domain gets automatic SSL and can be linked to your AI-generated sites.", icon: CheckCircle2, position: "center" },
];

export const DASHBOARD_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to your Dashboard", description: "This is your real-time business command center. Get an instant overview of leads, messages, contacts, and pipeline performance — all updated live as your business grows.", icon: LayoutTemplate, position: "center" },
  { id: "metrics", title: "Key Performance Metrics", description: "Track the numbers that matter most: total leads captured, messages sent and received, active contacts, and total pipeline value. These metrics update in real-time across all your accounts.", icon: Target, position: "center" },
  { id: "roi-charts", title: "ROI & Performance Charts", description: "Visualize your daily trends with interactive charts showing leads generated and messages exchanged over time. Spot growth patterns, identify peak days, and measure campaign ROI at a glance.", icon: TrendingUp, position: "center" },
  { id: "quick-actions", title: "Quick Actions", description: "Access your most-used tools instantly. Jump to creating a new contact, sending a message, launching a campaign, or building a workflow — all with one click from the dashboard.", icon: Zap, position: "center" },
  { id: "pipeline", title: "Pipeline Overview", description: "See a visual summary of your deal pipeline right from the dashboard. Track how many deals are in each stage and monitor your total pipeline value without leaving the overview.", icon: Layers, position: "center" },
  { id: "done", title: "Dashboard Mastered!", description: "You now know how to read your business health at a glance. Explore other tools from the sidebar to dive deeper into leads, campaigns, and automations.", icon: CheckCircle2, position: "center" },
];

export const PIPELINE_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to Pipeline Manager", description: "Track and manage your deals visually with a kanban-style pipeline. Drag deals between stages, monitor values, and close more business with a clear overview of every opportunity.", icon: Columns, position: "center" },
  { id: "stages", title: "Pipeline Stages", description: "Your pipeline is organized into stages: Lead, Contacted, Qualified, Proposal, Won, and Lost. Each stage represents where a deal is in your sales process — move deals forward as they progress.", icon: Layers, position: "center" },
  { id: "add-deal", title: "Create a New Deal", description: "Add a new deal by entering the deal name, expected value, and associated contact. Every deal starts in the Lead stage and moves through your pipeline as the relationship progresses.", icon: Plus, position: "center" },
  { id: "drag-drop", title: "Move Deals Between Stages", description: "Drag and drop deals between columns to update their status instantly. Move a deal from Lead to Contacted after your first outreach, or from Proposal to Won when you close it.", icon: GripVertical, position: "center" },
  { id: "deal-details", title: "Deal Information", description: "Click any deal card to view and edit its details: deal name, value, contact info, notes, and stage history. Keep all your deal intelligence organized in one place.", icon: FileText, position: "center" },
  { id: "done", title: "Pipeline Pro!", description: "You're ready to manage your sales pipeline like a pro. Add your deals, track their progress through each stage, and close more business with visual deal management.", icon: CheckCircle2, position: "center" },
];

export const EMAIL_CAMPAIGNS_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to Email Campaigns", description: "Design, send, and track email marketing campaigns to your audience. Create beautiful email blasts, schedule delivery, and measure performance — all from one dashboard.", icon: Mail, position: "center" },
  { id: "create", title: "Create a Campaign", description: "Start a new campaign by setting the campaign name, email subject line, and selecting your target audience. Choose from your contact lists or segments to reach the right people.", icon: Plus, position: "center" },
  { id: "editor", title: "Email Editor", description: "Write and format your email content using the built-in editor. Add text, images, buttons, and links to create professional-looking emails that drive engagement and conversions.", icon: FileText, position: "center" },
  { id: "schedule", title: "Schedule or Send Now", description: "Choose when your campaign goes out. Send immediately for time-sensitive announcements, or schedule for a future date and time to hit your audience at the perfect moment.", icon: Clock, position: "center" },
  { id: "analytics", title: "Campaign Analytics", description: "Track your campaign performance with detailed analytics: open rates, click-through rates, bounce rates, and conversions. See which emails resonate and optimize future campaigns.", icon: BarChart, position: "center" },
  { id: "done", title: "Email Marketing Ready!", description: "You're all set to launch email campaigns that convert. Create your first campaign, craft compelling content, and watch your engagement metrics grow.", icon: CheckCircle2, position: "center" },
];

export const INTEGRATIONS_STEPS: TutorialStep[] = [
  { id: "welcome", title: "Welcome to Integrations Hub", description: "Connect your favorite third-party services to supercharge your workflow. Link Google Workspace, communication tools, and marketing platforms — all managed from one central hub.", icon: Plug, position: "center" },
  { id: "google", title: "Google Workspace", description: "Connect your Google services: Calendar for appointment syncing, Gmail for email integration, Sheets for data exports, Maps for location services, and Business Profile for review management.", icon: Globe, position: "center" },
  { id: "communication", title: "Communication Tools", description: "Integrate your communication stack: Twilio for SMS and voice capabilities, and Slack for team notifications and alerts. Keep your team connected and your customers engaged.", icon: MessageSquare, position: "center" },
  { id: "marketing", title: "Marketing & Analytics", description: "Power up your marketing with Mailchimp for email automation, Facebook for social ads and lead capture, and Zapier for connecting thousands of additional apps to your workflows.", icon: Megaphone, position: "center" },
  { id: "connect", title: "Connect a Service", description: "Click the Connect button on any integration card to begin the authorization process. Follow the prompts to grant access, and the integration will be live in seconds.", icon: Link, position: "center" },
  { id: "done", title: "Fully Connected!", description: "Your integrations hub is ready. Connect the services you use most to automate data flow, streamline communication, and unlock the full power of your platform.", icon: CheckCircle2, position: "center" },
];
